{
  "comments": [
    {
      "key": {
        "uuid": "da6895a0_75567ad3",
        "filename": "/COMMIT_MSG",
        "patchSetId": 1
      },
      "lineNbr": 15,
      "author": {
        "id": 16907
      },
      "writtenOn": "2016-10-24T14:24:18Z",
      "side": 1,
      "message": "I think this patch might fix the following bug too:\n\n- Nova issue - InternalError: (1049, u\"Unknown database \u0027nova_api\u0027\") https://bugs.launchpad.net/devstack/+bug/1620028",
      "range": {
        "startLine": 15,
        "startChar": 0,
        "endLine": 15,
        "endChar": 21
      },
      "revId": "88e5be5fbb2fd09a424f775e62d503735f1e9f64",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    }
  ]
}