{
  "comments": [
    {
      "key": {
        "uuid": "dfd5e7cf_115a76f2",
        "filename": "/COMMIT_MSG",
        "patchSetId": 1
      },
      "lineNbr": 11,
      "author": {
        "id": 7118
      },
      "writtenOn": "2019-01-10T06:20:23Z",
      "side": 1,
      "message": "Example of the failure @ [1]\n\nOr you can just run it under python3 manually\n\n[1] http://logs.openstack.org/68/626068/2/check/nodepool-functional-py35/feb318d/controller/logs/devstacklog.txt.gz#_2018-12-19_09_45_13_935",
      "revId": "8fe94669d88e16108e7170709940232b0973df36",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    }
  ]
}