{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "a9690377_2707010d",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 17685
      },
      "writtenOn": "2024-12-03T15:30:55Z",
      "side": 1,
      "message": "clean cherry pick from wallaby, where the patch has merged. LGTM. Thanks Lajos o/",
      "revId": "a0b1fef715bb5ed951d377e4c712a3513238fd8b",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "e3574a02_aee372f9",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 17685
      },
      "writtenOn": "2024-12-03T16:58:00Z",
      "side": 1,
      "message": "recheck - openstacksdk-functional-devstack failed with two test cases, both with the same error (test_get and test_create_incremental):\n\nopenstack.exceptions.ResourceFailure: Backup:a2a59de4-d8db-48b2-b743-e5ea5a35a83a transitioned to failure state error",
      "revId": "a0b1fef715bb5ed951d377e4c712a3513238fd8b",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    }
  ]
}