{
  "comments": [
    {
      "key": {
        "uuid": "5fc1f717_f36404bb",
        "filename": "inc/python",
        "patchSetId": 4
      },
      "lineNbr": 53,
      "author": {
        "id": 5803
      },
      "writtenOn": "2019-03-28T11:04:24Z",
      "side": 1,
      "message": "I have doubts about we have real distro differences today.",
      "revId": "a30dd1cc96a75d565ae924e4698c4208150e5564",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5fc1f717_456669ef",
        "filename": "inc/python",
        "patchSetId": 4
      },
      "lineNbr": 53,
      "author": {
        "id": 14807
      },
      "writtenOn": "2019-03-28T13:35:38Z",
      "side": 1,
      "message": "will the following do the work ? I dont have Python3 installed in my setup at this moment\n# dirname  $(which python)",
      "parentUuid": "5fc1f717_f36404bb",
      "revId": "a30dd1cc96a75d565ae924e4698c4208150e5564",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5fc1f717_85b211e4",
        "filename": "inc/python",
        "patchSetId": 4
      },
      "lineNbr": 53,
      "author": {
        "id": 5803
      },
      "writtenOn": "2019-03-28T13:50:07Z",
      "side": 1,
      "message": "/usr/local/bin ALL py3 , /usr/bin ALL py2 . I do not know about exception.\n\nf27 EoL.",
      "parentUuid": "5fc1f717_456669ef",
      "revId": "a30dd1cc96a75d565ae924e4698c4208150e5564",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    }
  ]
}