{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "d887a87b_01ea632c",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 4393
      },
      "writtenOn": "2023-08-04T16:53:29Z",
      "side": 1,
      "message": "recheck guest kernel crashed but no http timeouts to examine",
      "revId": "c3b0b9034e6b35187a125283e55056ae90cbbc4a",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "2830afcf_61758a6d",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 4393
      },
      "writtenOn": "2023-08-04T18:41:04Z",
      "side": 1,
      "message": "recheck get another data point",
      "revId": "c3b0b9034e6b35187a125283e55056ae90cbbc4a",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "7aa0c270_2a9038e4",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 4393
      },
      "writtenOn": "2023-08-07T16:16:05Z",
      "side": 1,
      "message": "recheck get another data point",
      "revId": "c3b0b9034e6b35187a125283e55056ae90cbbc4a",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "dd5ee567_2d219703",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 4393
      },
      "writtenOn": "2023-08-08T13:31:14Z",
      "side": 1,
      "message": "recheck tempest fixes merged",
      "revId": "c3b0b9034e6b35187a125283e55056ae90cbbc4a",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "0531ac6f_bafa5c6c",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 8556
      },
      "writtenOn": "2023-08-08T17:19:45Z",
      "side": 1,
      "message": "this lgtm, it will help to know and debug the issues",
      "revId": "c3b0b9034e6b35187a125283e55056ae90cbbc4a",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "466f647e_2d647b51",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 22873
      },
      "writtenOn": "2023-08-08T18:53:00Z",
      "side": 1,
      "message": "great idea, let\u0027s do it",
      "revId": "c3b0b9034e6b35187a125283e55056ae90cbbc4a",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "5cb7ecfa_bc25f376",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 4393
      },
      "writtenOn": "2023-08-08T22:44:13Z",
      "side": 1,
      "message": "recheck unrelated database error\n\nNot sure what this is from, but clearly not related to this patch:\n```\nAug 08 21:09:16.087799 np0034897097 devstack@n-api.service[89219]: ERROR nova.api.openstack.wsgi pymysql.err.IntegrityError: (1452, \u0027Cannot add or update a child row: a foreign key constraint fails (`nova_cell0`.`instance_actions`, CONSTRAINT `fk_instance_actions_instance_uuid` FOREIGN KEY (`instance_uuid`) REFERENCES `instances` (`uuid`))\u0027)\n```",
      "revId": "c3b0b9034e6b35187a125283e55056ae90cbbc4a",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    }
  ]
}