{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "75ea2f03_a540d26c",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 13252
      },
      "writtenOn": "2022-02-15T21:55:36Z",
      "side": 1,
      "message": "If this is a bug on aarch64, maybe be conservative and only apply the workaround there? I\u0027m also wondering whether this might be an intentional behavior somehow or whether it should be reported as pip bug.",
      "revId": "d58dfd13007648b0609279e2202bc0aab4e6614d",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    }
  ]
}