{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "43109458_c11ac45c",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 27615
      },
      "writtenOn": "2025-02-05T09:23:08Z",
      "side": 1,
      "message": "recheck incremental backup test failed in devstack-platform-debian-bullseye, looks unrelated",
      "revId": "efb89d2297ed10ff108f5131c0f3c70247011fc1",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "2533d2ed_fef0a206",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 27615
      },
      "writtenOn": "2025-02-05T20:28:02Z",
      "side": 1,
      "message": "recheck looks like connection broke during devstack setup\n\n2025-02-05 19:18:56.650526 | controller | venv-tempest installdeps: -chttps://releases.openstack.org/constraints/upper/master, -r/opt/stack/tempest/requirements.txt\n2025-02-05 19:19:04.831163 | controller | ERROR: invocation failed (exit code 1), logfile: /opt/stack/tempest/.tox/tempest/log/venv-tempest-1.log\n2025-02-05 19:19:04.831203 | controller | \u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d log start \u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\n2025-02-05 19:19:04.831219 | controller | WARNING: Retrying (Retry(total\u003d4, connect\u003dNone, read\u003dNone, redirect\u003dNone, status\u003dNone)) after connection broken by \u0027NewConnectionError(\u0027\u003cpip._vendor.urllib3.connection.HTTPSConnection object at 0x7f7fa06859c0\u003e: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution\u0027)\u0027: /constraints/upper/master\n2025-02-05 19:19:04.831227 | controller | WARNING: Retrying (Retry(total\u003d3, connect\u003dNone, read\u003dNone, redirect\u003dNone, status\u003dNone)) after connection broken by \u0027NewConnectionError(\u0027\u003cpip._vendor.urllib3.connection.HTTPSConnection object at 0x7f7fa0687970\u003e: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution\u0027)\u0027: /constraints/upper/master\n2025-02-05 19:19:04.831234 | controller | WARNING: Retrying (Retry(total\u003d2, connect\u003dNone, read\u003dNone, redirect\u003dNone, status\u003dNone)) after connection broken by \u0027NewConnectionError(\u0027\u003cpip._vendor.urllib3.connection.HTTPSConnection object at 0x7f7fa0685330\u003e: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution\u0027)\u0027: /constraints/upper/master\n2025-02-05 19:19:04.831243 | controller | WARNING: Retrying (Retry(total\u003d1, connect\u003dNone, read\u003dNone, redirect\u003dNone, status\u003dNone)) after connection broken by \u0027NewConnectionError(\u0027\u003cpip._vendor.urllib3.connection.HTTPSConnection object at 0x7f7fa0685150\u003e: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution\u0027)\u0027: /constraints/upper/master\n2025-02-05 19:19:04.831249 | controller | WARNING: Retrying (Retry(total\u003d0, connect\u003dNone, read\u003dNone, redirect\u003dNone, status\u003dNone)) after connection broken by \u0027NewConnectionError(\u0027\u003cpip._vendor.urllib3.connection.HTTPSConnection object at 0x7f7fa06870a0\u003e: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution\u0027)\u0027: /constraints/upper/master\n2025-02-05 19:19:04.831256 | controller | ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host\u003d\u0027releases.openstack.org\u0027, port\u003d443): Max retries exceeded with url: /constraints/upper/master (Caused by NewConnectionError(\u0027\u003cpip._vendor.urllib3.connection.HTTPSConnection object at 0x7f7fa0686bc0\u003e: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution\u0027))",
      "revId": "efb89d2297ed10ff108f5131c0f3c70247011fc1",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "8282ba14_e3c886aa",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 22873
      },
      "writtenOn": "2025-02-13T14:18:14Z",
      "side": 1,
      "message": "recheck looks like a random issue, one test failed with \"failed to import on stores\"",
      "revId": "efb89d2297ed10ff108f5131c0f3c70247011fc1",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "bd0da44f_22f8edbc",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 22873
      },
      "writtenOn": "2025-02-14T10:53:31Z",
      "side": 1,
      "message": "recheck volume timeout",
      "revId": "efb89d2297ed10ff108f5131c0f3c70247011fc1",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "15fde6d1_104e6616",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 5314
      },
      "writtenOn": "2025-02-14T22:41:09Z",
      "side": 1,
      "message": "recheck devstack-platform-debian-bookworm - looks like a transient failure in an object store test",
      "revId": "efb89d2297ed10ff108f5131c0f3c70247011fc1",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "f7bd82c4_65ca646d",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 22873
      },
      "writtenOn": "2025-02-15T09:57:32Z",
      "side": 1,
      "message": "recheck random deployment error in ironic-tempest-bios-ipmi-direct-tinyipa job",
      "revId": "efb89d2297ed10ff108f5131c0f3c70247011fc1",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "ec2d891c_82fbee81",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 13252
      },
      "writtenOn": "2025-02-19T05:42:56Z",
      "side": 1,
      "message": "recheck ironic failure seems to persist, we might need to drop the job",
      "revId": "efb89d2297ed10ff108f5131c0f3c70247011fc1",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "45a896be_2abde5a6",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 8556
      },
      "writtenOn": "2025-02-19T19:05:37Z",
      "side": 1,
      "message": "recheck ssh timeout in test_stable_device_rescue_disk_virtio_with_volume_attached",
      "revId": "efb89d2297ed10ff108f5131c0f3c70247011fc1",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "005bfb44_a95dc47e",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 13252
      },
      "writtenOn": "2025-03-05T18:28:22Z",
      "side": 1,
      "message": "recheck dependency in sdk job should be fixed",
      "revId": "efb89d2297ed10ff108f5131c0f3c70247011fc1",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    }
  ]
}