{
  "comments": [
    {
      "key": {
        "uuid": "AAAARn//8aU\u003d",
        "filename": "lib/horizon",
        "patchSetId": 20
      },
      "lineNbr": 136,
      "author": {
        "id": 6735
      },
      "writtenOn": "2013-08-19T21:54:01Z",
      "side": 1,
      "message": "This is causing current failure - since VENV_PATH ends up with two site-packages, causing the sed below to fail.\npossibly use $VIRTUAL_ENV/lib/python*/site-packages ?",
      "revId": "efc10cc2639effae2720b7ffeeb1a216cbdfd712",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "AAAARn//8ck\u003d",
        "filename": "lib/nova",
        "patchSetId": 20
      },
      "lineNbr": 458,
      "author": {
        "id": 6735
      },
      "writtenOn": "2013-08-19T21:45:53Z",
      "side": 1,
      "message": "Must execute get_python_exec_prefix",
      "revId": "efc10cc2639effae2720b7ffeeb1a216cbdfd712",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543",
      "unresolved": false
    }
  ]
}